### ISSUE TITLE
How to create refCounts?

### ISSUE THREAD

**Issue by vierja** [dbpedia/lookup#26]
I am trying to build an index for Spanish data, but I can't seem to find a way to build refCount information needed to properly sorting the data.

All I found was a page-links_es.nt.bz2 file containing wikiPageWikiLink triples.

**Comment by sandroacoelho** [comment]
Hi @vierja 

In order to build a new index, you just need to concatenate all data and sort by URI and run the indexer command as in the README file. 

Unfortunately, we don't have i18n for Lookup, but you can do changing  the namespace "http://dbpedia.org/" for the target language (Sorry for that). We will improve it soon and you are invited to help us, if you want  :+1: 

*I saw what you're looking for somewhere. I will try to find it... Once I have the answer, I will let you know here

**Comment by HugoSousa** [comment]
Is the refCount information included in the pre-built indexes? I tried to locally mirror the service (for English, the default language) following the instructions in the README, but the refCount and the description seem to be empty.

**Comment by sandroacoelho** [comment]
Hi @vierja, @HugoSousa ,  I have an answer to you:

 A few years ago, RefCounts was provided by [pignlproc project](https://github.com/dicode-project/pignlproc) and seems that this project does not active development anymore.

However, @jodaiber (From DBpedia Spotlight) told us that a startup in the US (diffbot) rewrote it to run on a single machine with the same output.  The code is available [here](https://github.com/jodaiber/wikistatsextractor) and it runs automatically for most languages once a month. These dumps are available [here](http://spotlight.sztaki.hu/downloads/latest_data/).

@HugoSousa : I will rebuild our index asap

Best,
